# Generated by Django 5.1.2 on 2025-03-08 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('czech_score', models.IntegerField()),
                ('math_score', models.IntegerField()),
                ('date_taken', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('min_czech_score', models.IntegerField(default=0)),
                ('min_math_score', models.IntegerField(default=0)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('czech_score', models.IntegerField()),
                ('math_score', models.IntegerField()),
                ('first_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_choice_students', to='frontend.school')),
                ('second_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_choice_students', to='frontend.school')),
            ],
        ),
    ]
