# Generated by Django 5.1.2 on 2025-03-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='min_czech_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimální skóre z češtiny'),
        ),
        migrations.AlterField(
            model_name='school',
            name='min_math_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimální skóre z matematiky'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
