# Generated by Django 5.1.2 on 2024-12-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_school_city_remove_school_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
