# Generated by Django 5.1.2 on 2025-03-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_student_third_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='min_czech_score',
        ),
        migrations.RemoveField(
            model_name='school',
            name='min_math_score',
        ),
        migrations.AddField(
            model_name='school',
            name='min_czech_score_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimální skóre z češtiny 1'),
        ),
        migrations.AddField(
            model_name='school',
            name='min_czech_score_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimální skóre z češtiny 2'),
        ),
        migrations.AddField(
            model_name='school',
            name='min_czech_score_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimální skóre z češtiny 3'),
        ),
        migrations.AddField(
            model_name='school',
            name='min_math_score_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimální skóre z matematiky 1'),
        ),
        migrations.AddField(
            model_name='school',
            name='min_math_score_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimální skóre z matematiky 2'),
        ),
        migrations.AddField(
            model_name='school',
            name='min_math_score_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimální skóre z matematiky 3'),
        ),
    ]
